### ISSUE TITLE
TTL parameter of  SET -cmd is not supported 

### ISSUE THREAD

**Issue by teemukin65** [fppt/jedis-mock#85] opened 2020-02-21 11:33 UTC
TTL -related parameters of Redis [SET - command](https://redis.io/commands/set) are not supported in the [RO_set](https://github.com/fppt/jedis-mock/blob/master/src/main/java/com/github/fppt/jedismock/operations/RO_set.java#L15)

I encountered this when updating my Spring Boot application to Spring Boot version 2.2.4. This application uses Redis Cache, which used separate Redis SET & EXPIRE commands when storing the item to the cache, but now at Spring Boot (& Spring Data) version 2.2.4 the storing is done using SET cmd with TTL parameter included. And now the jedis-mock can't serve so well in the testing of my microservice cache functionalities.

**Comment by inponomarev** [comment] 2021-12-11 23:49
duplicate of #91, fixed in 0.1.24

**Closed by inponomarev** 2021-12-11 23:49 UTC
