### ISSUE TITLE
ConcurrentModificationException when calling Scan

### ISSUE THREAD

**Issue by wcedmisten** [fppt/jedis-mock#131] opened 2021-05-17 13:48 UTC
The full stack trace is:

```
Exception in thread "Thread-5" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.github.fppt.jedismock.storage.RedisBase.keys(RedisBase.java:26)
	at com.github.fppt.jedismock.operations.RO_scan.doOptionalWork(RO_scan.java:34)
	at com.github.fppt.jedismock.operations.AbstractRedisOperation.execute(AbstractRedisOperation.java:45)
	at com.github.fppt.jedismock.server.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:43)
	at com.github.fppt.jedismock.server.RedisClient.run(RedisClient.java:54)
	at java.lang.Thread.run(Thread.java:748)
```

I believe this error is caused by this line:

https://github.com/fppt/jedis-mock/pull/123/files#diff-fac1cff9857cfd05f42b232bdd1ca0bde2e0e05bd66ec33990c8855dd3919ccbR29

from the recent https://github.com/fppt/jedis-mock/pull/123

This StackOverflow question seems relevant to the issue as well: https://stackoverflow.com/questions/602636/why-is-a-concurrentmodificationexception-thrown-and-how-to-debug-it

One possible solution is to copy the slice before iterating over it, so that the key is not deleted while iterating.

**Comment by wcedmisten** [comment] 2021-05-17 14:39
Somehow cloning my repository again fixed this error, and I'm unable to reproduce this, so feel free to close the issue if you can't either.

**Comment by inponomarev** [comment] 2021-07-02 07:19
I think this deletion is covered by this test

https://github.com/fppt/jedis-mock/pull/123/files#diff-6091083a6985b7bba5194773c9c204d2b60d7cbf506d4ca9bd49f55fd6e9b200R203

I'm closing this now, since it's not reproduced...

**Closed** 2021-07-02 07:19 UTC

**Comment by wcedmisten** [comment] 2021-07-08 13:43
@inponomarev Do you know if this library is intended to me thread-safe? I can consistently reproduce this in a multithreaded test, but I'm not sure if that's undefined behavior for this library. That also makes it hard to add to the existing test suite.

If it's not intended as thread-safe, maybe we could add a note in the docs mentioning this.
