### ISSUE TITLE
Incompatible with LettuceClient 6.x - Unsupported operation 'hello'

### ISSUE THREAD

**Issue by mikeluoma** [fppt/jedis-mock#104] opened 2020-11-13 11:12 UTC
Hi,

We're attempting to upgrade from v5.3.3.RELEASE of the lettuce redis client to v6.0.1.RELEASE.

When running unit tests with jedis-mock, we have the following exception:

```
    11:03:02.189 [lettuce-nioEventLoop-40-1] DEBUG io.lettuce.core.AbstractRedisClient - Connecting to Redis at localhost:50385, initialization: localhost:50385
    java.util.concurrent.CompletionException: io.lettuce.core.RedisCommandExecutionException: Unsupported operation 'hello'
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.lettuce.core.RedisHandshake.lambda$tryHandshakeResp3$1(RedisHandshake.java:105)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)
        at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
        at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
        at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:704)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:639)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560)
```
Per readme, submitting an issue.  Thanks!

**Comment by sebastian-brandt** [comment] 2021-03-06 14:23
This seems caused by Lettuce 6 using RESP3 protocol  (found out about that [here](https://github.com/lettuce-io/lettuce-core/issues/1543#issuecomment-741635020)) and jedis-mock not supporting it.
You might downgrade to RESP2 protocol as a workaround:
```
RedisClient redisClient = RedisClient.create(...);
redisClient.setOptions(ClientOptions.builder().protocolVersion(ProtocolVersion.RESP2).build());
```
With RESP2 set as protocol, jedis-mock works.

**Comment by inponomarev** [comment] 2021-05-08 12:18
Hi, I implemented `hello` support in a way that it always returns RESP2 as a supported protocol. Thus it is now possible to use Lettuce 6.x without any additional configuration. The fix will be included in 0.1.19 release

**Closed** 2021-05-08 12:18 UTC

**Comment by parmar049** [comment] 2021-07-12 11:21
> Hi, I implemented `hello` support in a way that it always returns RESP2 as a supported protocol. Thus it is now possible to use Lettuce 6.x without any additional configuration. The fix will be included in 0.1.19 release

Hi Is this fix available? Facing same issue at my side.

**Comment by inponomarev** [comment] 2021-07-12 13:30
Hi @parmar049 which version are you using? the latest one (0.1.20) should work with Lettuce Client seamlessly, we even have a test for it.

**Comment by inponomarev** [comment] 2021-07-12 16:49
My guess: you have an older version of jedis-mock somewhere on your classpath.
Unsupported operation 'XXX' occurs only when operation is not known to jedis-mock.
'hello' is a supported operation.

BTW did you try this workaraound? https://github.com/fppt/jedis-mock/issues/104#issuecomment-791960911

Investigate what's on your classpath!

**Comment by parmar049** [comment] 2021-07-13 09:12
Thanks @inponomarev It get resolved, looks like it was not updating to latest version 0.1.20, had to delete manually from .m2 folder and clean it again. its fixed now.
