### ISSUE TITLE
`XREAD $` fails for an empty stream

### ISSUE THREAD

**Issue by uhrm** [fppt/jedis-mock#540] opened 2024-10-11 08:39 UTC
I'm using jedis-mock in my unit tests. The code to be tested is using the Jedis client to make an XREAD call as follows:
```java
client.xread(XReadParams.xReadParams().block(0).count(1), Map.of("stream:key", StreamEntryID.LAST_ENTRY))
```
With this ID, the code never receives entries sent by the test driver. When I change the code to
```java
client.xread(XReadParams.xReadParams().block(0).count(1), Map.of("stream:key", new StreamEntryID()))
```
to read from the beginning, it works as expected.

Is this not supported?

**Comment by inponomarev** [comment] 2024-10-14 11:06
Dear @uhrm , this is supported, and the quick test I just created cannot reproduce the issue. Could you please send more context, e. g. a reproducer of the problem.

**Comment by uhrm** [comment] 2024-10-15 09:59
I'm essentially doing the following:

```java
package test.jedis;

import java.io.IOException;
import java.net.Inet4Address;
import java.time.Duration;
import java.util.Map;

import com.github.fppt.jedismock.RedisServer;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.StreamEntryID;
import redis.clients.jedis.params.XAddParams;
import redis.clients.jedis.params.XReadParams;

public class App {

  private static final RedisServer REDIS = RedisServer
      .newRedisServer(6399, Inet4Address.getLoopbackAddress());

  private static void handler() {
    try (var client = new Jedis("localhost", 6399)) {
      System.out.println("*** Waiting for Redis message...");
      var entries = client.xread(XReadParams.xReadParams().block(0).count(1), Map.of("test:jedis", StreamEntryID.LAST_ENTRY));
      if (entries.isEmpty()) {
        System.out.println("*** XREAD returned with no entries");
        return;
      }
      if (entries.size() != 1) {
        System.out.println("Received more than one stream message"); // should never happen
        return;
      }
      System.out.printf("*** XREAD message: key=%s, value=%s\n", entries.getFirst().getKey(), entries.getFirst().getValue().getFirst());
    }
    System.out.println("*** Exiting handler");
  }

  public static void main(String[] args) throws IOException, InterruptedException {
    System.out.println("*** Starting Jedis server...");
    REDIS.start();
    System.out.println("*** Starting handler thread...");
    new Thread(App::handler).start();
    Thread.sleep(Duration.ofSeconds(1L));
    System.out.println("*** Sending test message...");
    try (var client = new Jedis("localhost", 6399)) {
      client.xadd("test:jedis", Map.of("message", "Test 123"), XAddParams.xAddParams());
    }
    System.out.println("*** Exiting main");
  }
}
```
This blocks forever on the `xread` call in the handler thread. Changing the xread call to
```java
var entries = client.xread(XReadParams.xReadParams().block(0).count(1), Map.of("test:jedis", new StreamEntryID()));
```
works as expected.

Only dependency is `com.github.fppt:jedis-mock:1.1.4` (with transient `redis.clients:jedis:5.1.5`). Running with JDK 21 (Azul).

**Comment by inponomarev** [comment] 2024-10-26 10:58
Hi @uhrm thanks for your report and your reproducer. The problem indeed reproduced only if stream was initally empty. Fix is on the way, expect the release soon!

**Comment by inponomarev** [comment] 2024-10-26 12:08
Fixed in v. 1.1.5

**Closed by inponomarev** 2024-10-26 12:08 UTC
Labels: bug, info-needed
